### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by lvivier** [Retsly/retsly-js-sdk#60]
## Overview

TODO

## Tasks

- [ ] Refactor to work in node.js and browser
- [ ] Use our updated style guide
- [ ] Must work with [Tonic](https://tonicdev.com/)
- [ ] Rework API to work like [retsly/js-sdk](/retsly/js-sdk)
